sudo: required

language: node_js

node_js:
  - "11"

services:
  - docker

before_install:
  - docker build -t test . && docker run test

# language: node_js
# node_js:  
#   - "8"  
#   - "9"
# script:  
#   - npm test